### ISSUE TITLE
Tutorial part 1 - Orientation - "Teaching Tomster" image not displaying

### ISSUE THREAD

**Issue by jafarlow** [ember-learn/super-rentals-tutorial#125]
### ISSUE:

I'm working through the tutorial to learn Ember, and I've come to the bottom of the Orientation page and encountered this statement: 

> "The image should also show up in the welcome page we have been working on. You may need to do a manual refresh for the browser to pick up the new file"

This is combined with a screenshot:
![styled-with-tomster@2x](https://user-images.githubusercontent.com/33103791/73098356-38235b80-3eb7-11ea-8a7d-3a583dac48f8.png)

When following the instructions in the tutorial, this image will not display as it is set as the background for a `<div>` which currently has no height. 

Tutorial code:
**handlebars**
```hbs
<div class="jumbo">
  <div class="right tomster"></div>
  <h2>Welcome to Super Rentals!</h2>
  <p>We hope you find exactly what you're looking for in a place to stay.</p>
</div>
```

**CSS**
```css
.tomster {
  background-image: url(../assets/images/teaching-tomster.png);
}
```

**result**
![Screenshot from 2020-01-24 14-35-48](https://user-images.githubusercontent.com/33103791/73098196-dcf16900-3eb6-11ea-8b46-fb25c5a2ee15.png)

---
When testing if an image displays when the height is modified, it does, but shows in it's natural position (left) and it tiles it. Modifying the height to check if the image was linked properly:
**CSS**
```css
.tomster {
  height: 300px;
  background-image: url(../assets/images/teaching-tomster.png);
}
```

**result**
![Screenshot from 2020-01-24 14-37-58](https://user-images.githubusercontent.com/33103791/73098330-2641b880-3eb7-11ea-9ed9-23cf7f2bdad6.png)

### PROPOSAL:

There are two possibilities I can see here to resolve this. The first would be to include all the CSS required to make the Tomster appear as it does in the tutorial's screenshot. The other is to mention that's how it'll look once some other styling is applied, which will be supplied later in the tutorial.

I'm leaving my code as it is in the tutorial, in the hopes that I'll encounter other CSS later in the tutorial which will put it to rights. 

I wanted to flag this as the difference in reality and expectation is enough that it halts all progress in the tutorial, switching from follow-along mode to debug mode.

**Comment by chancancode** [comment]
Hi @jafarlow, I transferred your issue here since this is where the tutorial currently live. 

This is expected to work – the screenshots you see are captured using a real browser after following the same steps in the tutorial text. I suspect the problem is you didn't download the full CSS file as prompted in this part of the tutorial:

> Fortunately, our designer sent us some CSS to use, so we can **download the stylesheet file** and copy it into `app/styles/app.css`. This file has all the styles we need for building the rest of the app.

Do you mind checking that?

**Comment by jafarlow** [comment]
Copying in the whole file does work. The way the information was provided, it looked like we were supposed to only copy in the CSS in the snippet with the rest being provided piecemeal later in the tutorial, like how the rest of the code is presented. That's how I interpreted the `/* ...snip... */` bit in the code block to mean.

Rereading what you quoted there does make it seem I should've copied the whole thing. Thanks for confirming that I need to copy the whole file at the outset!

**Comment by chancancode** [comment]
I think we can improve the `/* ...snip... */` part to avoid this confusion. I think we can either add a short comment at the top that says you should download the file, or we can replace the `/* ...snip... */` comment with something else. The source is located [here](https://github.com/ember-learn/super-rentals-tutorial/blob/master/src/markdown/tutorial/part-1/01-orientation.md). If you have any ideas, please feel free to propose a change with a pull request!

**Comment by chancancode** [comment]
Related: #100
