### ISSUE TITLE
Deployment step is missing.

### ISSUE THREAD

**Issue by andrasio** [ember-learn/super-rentals-tutorial#134]
I wasn't sure where to ask (there is another `super-rentals` repository under `ember-learn`)

If you browse the ember learn site [here](https://emberjs.com/learn/). 

You will see **"Follow our tutorial to build, and deploy, your first Ember.js application!"** next to the Tutorial link (the super-rentals guide containing Part 1 and Part 2)

The guide ends Part 2 with **Provider Components** and **Recap** sections and no other sections (At least I wasn't able to find) contains guide for deploying.

On the other hand, clicking on "Quick Start Guide" does cover deployment.

Also, I'm using Safari and if you browse specifically a section of the super-rentals tutorial the sidebar on the left under "Tutorial" is not collapsed by default (maybe it should be or maybe not).

**Comment by chancancode** [comment]
Hi @andrasio you are right, that chapter is currently missing. I've opened #137 to collect the ideas of what needs to be covered. Assuming you got to the end of the last chapter, the app _should_ be ready for deployment using Netlify (or other similar services like Heroku). Do you mind giving Netlify a go, and document any thoughts, friction, questions, problems etc on issue #137 so we know what we need to cover there?

**Comment by andrasio** [comment]
@chancancode Thanks! Sure, will do so.

**Comment by andrasio** [comment]
@chancancode Netlify deployment went smoothly. Not much to say regarding that for the issue #137.
