### ISSUE TITLE
Small typo in Tutorial [BUG]

### ISSUE THREAD

**Issue by wbguerin** [ember-learn/super-rentals-tutorial#157]
An URL in the tutorial confusingly gives a path component in the plural when it should be singular.

URL: [https://guides.emberjs.com/release/tutorial/part-1/interactive-components/](https://guides.emberjs.com/release/tutorial/part-1/interactive-components/)

Current text: This generated a JavaScript file with the same name as our component's template at app/components/**rentals**/image.js. 

... should be rental (singular).

**Comment by chancancode** [comment]
Good catch! If you have a moment, you can edit the file here: https://github.com/ember-learn/super-rentals-tutorial/edit/master/src/markdown/tutorial/part-1/06-interactive-components.md

**Comment by ijlee2** [comment]
Let me close this issue in favor of a new issue with a few small tasks for Hacktoberfest.
