### ISSUE TITLE
add support for `--lang` flag

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/super-rentals-tutorial#173]
ensure that super-rentals supports the new `--lang` flag in ember-cli.

**Comment by fozy81** [comment]
Thanks @ijlee2 , will PR soon.

**Comment by fozy81** [comment]
Hi @ijlee2 I've prepared a [PR](https://github.com/ember-learn/super-rentals-tutorial/pull/174). I think it's okay and passes tests but please review. However...I wasn't  sure how to view it / build the super-rentals-tutorials locally to view it (?).
