### ISSUE TITLE
Update service inject support

### ISSUE THREAD

**Issue by locks** [ember-learn/super-rentals-tutorial#200]
The Ember 4.1 release brought with it `import { service } from '@ember/service';`, making it no longer necessary to alias `inject`.
See [RFC 752](https://emberjs.github.io/rfcs/0752-inject-service.html) for more information, and https://github.com/ember-learn/guides-source/pull/1766 for an example of how to update the imports.

**Comment by chancancode** [comment]
Closed by 6b294a5f0995a2da704fa0fde3a602531b2ed614
