### ISSUE TITLE
Finish prose for Part 1

### ISSUE THREAD

**Issue by jenweber** [ember-learn/super-rentals-tutorial#25]
Overall, the steps are:
- [ ] migrate content that is already written #24 
- [ ] Finish up written content for chapters 12-21. These “chapters” may be combined into the same pages. For example, Page 4 in the deployed guides === chapters 9-11.
- [ ] get feedback/proofreaders

The written content should follow the same style as Vaidehi and Godfrey have already written. The "chapters" of the tutorial correspond to commits [here](https://github.com/ember-learn/super-rentals/commits/octane-revised). See the full commit message for details.

**Comment by chancancode** [comment]
This is completed (other than getting feedback, which is ongoing)
